#   How to run:
#       docker stack deploy -c docker-compose.yaml --resolve-image never {stack_name}
version: "3.7"

services:
    jenkins:
        image: jenkins
        ports:
            - 38080:8080
            - 50000:50000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        secrets:
            - JENKINS_PASS
    shepherd:
        image: mazzolino/shepherd
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            placement:
                constraints:
                - node.role == manager
secrets:
    JENKINS_PASS:
        external: true
        name: JENKINS_PASS